import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Shield, Sword, HeartPulse, ExternalLink, CheckCircle2, CircleDot, BookOpen, Skull, TriangleAlert, ChevronDown, Zap, Target, Users, Sparkles } from 'lucide-react';
import './styles.css';
import './visual-polish.css';

const BASE_PATH = '/sobix-raidguide';
const warcraftLogs = 'https://www.warcraftlogs.com/zone/rankings/54';
const blizzard = 'https://worldofwarcraft.blizzard.com/en-gb/news/24294062/curse-of-ulatek-the-venomous-abyss-raid-goes-live-19-august';
const mythicTrap = 'https://www.mythictrap.com/en';
const wowhead = (slug) => `https://www.wowhead.com/guide/midnight/raids/venomous-abyss-${slug}-boss-strategy-abilities`;
const updated = '19.08.2026';
const baseRoles={tank:['Boss sauber positionieren und Tankmechaniken früh planen.'],healer:['Schadensspitzen antizipieren und Heil-CDs nach Mechanikfenstern planen.'],dps:['Mechanik vor Uptime spielen und Prioritätsziele konsequent fokussieren.']};
const bosses=[
{id:'nekzali',order:1,name:"Nek'zali the Soulcoiler",room:'Soulcoil Well',type:'2 Phasen + Intermission',summary:'Der zentrale Soulcoil Well bestimmt den Kampf. Adds und Spieler-Tode in seiner Nähe verschärfen das Ritual; bei 50 % folgt eine Intermission, danach eskaliert der Raidschaden.',firstPull:['Brunnen in der Mitte konsequent freihalten.','Restless Amani sofort stoppen und vom Brunnen weg töten.','Bei 50 % Echoes of Jawae fokussieren.','Defensive und Heil-CDs für Uncoiling aufheben.'],phases:[['Phase 1','Soulcoil Well kontrollieren und Adds stoppen.'],['50 % Intermission','Ritual of Awakening: Echoes of Jawae töten.'],['Phase 2','Uncoiling: steigender Raidschaden bis zum Kill.']],abilities:[['Soulcoil Well','Zentrale Gefahrenzone.'],['Soulcoil Rite','Raid-Schaden und Energiegewinn, wenn der Brunnen gespeist wird.'],['Restless Amani','Adds auf dem Weg zum Brunnen.'],['Ritual of Awakening','Intermission bei 50 %.'],['Uncoiling','Finale Phase mit steigendem Druck.'],['Ritual Burn','Heroisch/Mythisch: wiederholte Treffer werden gefährlicher.']],roles:{tank:['Boss und Adds vom Brunnen weg halten.','Add-Wege niemals durch die Mitte führen.'],healer:['Tode in Brunnennähe verhindern.','CDs für Intermission und Uncoiling staffeln.'],dps:['Adds vor Boss-DPS priorisieren, wenn sie den Brunnen bedrohen.','Echoes sofort fokussieren.']},difficulty:{heroic:'Ritual Burn verschärft wiederholte Soulcoil-Rite-Auslösungen.',mythic:'Feste Add-, Interrupt- und Positionszuweisungen sind entscheidend.'},sources:[['Blizzard',blizzard],['Wowhead',wowhead('nekzali-the-soulcoiler')],['Warcraft Logs',warcraftLogs]]},
{id:'sentinels',order:2,name:'Entombed Sentinels',room:'Sentinel Chamber',type:'2 Ziele + Intermission',summary:'Breath of Ula’tek und Blood of Ula’tek müssen getrennt werden. Zu dicht beieinander erhalten sie Ula’tek’s Dominance und nehmen 99 % weniger Schaden.',firstPull:['Raid in zwei feste Gruppen teilen.','Sentinels deutlich voneinander trennen.','Eigene Seite halten.','Helical Toxins nach Gruppenplan zusammenführen.'],phases:[['Geteilte Phase','Zwei Gruppen spielen getrennte Mechanikpakete.'],['100 Energie','Vitriolic Stasis: Bosse kommen zusammen und verteilen Helical Toxins.']],abilities:[["Ula'tek's Dominance",'Nahe Sentinels erleiden 99 % weniger Schaden.'],['Venom Coagulation','Erzeugt einen gefährlichen Slime.'],['Contaminate','Hoher wiederkehrender Raid-Schaden.'],['Blighted Blood','Dispellbarer Debuff.'],['Vitriolic Stasis','Intermission bei 100 Energie.'],['Helical Toxins','Anwendungen nach festem Plan kombinieren.']],roles:{tank:['Je einen Sentinel an einer Außenkante halten.','Nur zur Stasis zusammenführen.'],healer:['Heiler fest auf beide Gruppen verteilen.','Blighted Blood gezielt dispellen.'],dps:['Eigene Seite halten.','Venom Coagulation sofort priorisieren.']},difficulty:{heroic:'Zusätzliche Venom-Effekte erhöhen Raum- und Bewegungsdruck.',mythic:'Protovenom-Interaktionen verlangen feste Paarungen.'},sources:[['Wowhead',wowhead('entombed-sentinels')],['Warcraft Logs',warcraftLogs]]},
{id:'vashnik',order:3,name:'Vashnik the Malignant',room:'Chamber of Virulence',type:'Fountain-Rotation',summary:'Blood-, Shadow- und Flame-Fountains bestimmen das aktive Mechanikpaket. Die Bossposition vor 100 Energie entscheidet, welche zwei Fountains durch Imbibe genutzt werden.',firstPull:['Fountain-Reihenfolge vorher festlegen.','Boss früh in den nächsten Sektor bewegen.','Living Venoms vor der Mitte töten.','Imbibe als Raid-Schadenspeak behandeln.'],phases:[['Rotationszyklus','Boss bewegen → Imbibe → Living Venoms töten → nächste Position.']],abilities:[['Imbibe','Nutzt die zwei nächstgelegenen Fountains.'],['Infusion','Verstärkt das aktive Venom-Paket.'],['Living Venom','Add, das die Mitte nicht erreichen darf.'],['Malignant Burst','Fehlerfolge, wenn ein Venom die Mitte erreicht.']],roles:{tank:['Boss vor 100 Energie an den geplanten Sektor bewegen.'],healer:['CDs an Imbibe-Fenster koppeln.'],dps:['Living Venoms sofort priorisieren.']},difficulty:{heroic:'Mehr Überlappungen bestrafen schlechte Fountain-Rotationen.',mythic:'Fountain-Reihenfolge und Add-Zuweisungen vor Pull festlegen.'},sources:[['Wowhead',wowhead('vashnik-the-malignant')],['Warcraft Logs',warcraftLogs]]},
{id:'lost-explorers',order:4,name:'The Lost Explorers',room:"Mor'zahi's Tomb",type:'3 Ziele / Ressourcenmechanik',summary:'Drei besessene Tortollaner werden von Mor’zahi kontrolliert. Disgusting Fish brechen seine Konzentration; jeder Explorer kann nur einmal gefüttert werden.',firstPull:['Fisch-Reihenfolge festlegen.','Explorer räumlich trennen.','Mighty Thud korrekt soaken.','Frost-/Feuer-Effekte kontrolliert spielen.'],phases:[['Besessenheitszyklus','Mor’zahi kontrolliert einen Explorer; Disgusting Fish bricht die Kontrolle.'],['Nach einem Kill','Verbleibende Explorer eskalieren.']],abilities:[['Dark Whispers','Mor’zahi übernimmt einen Explorer.'],['Disgusting Fish','Begrenzte Ressource zum Brechen der Kontrolle.'],['Blink Nova','Raid-Schaden, der mit Entfernung sinkt.'],['Mighty Thud','Mehrere Soak-Sprünge.'],['Aura of Unity','Heroisch/Mythisch: nahe Explorer erhalten hohe Schadensreduktion.']],roles:{tank:['Explorer in getrennten Sektoren halten.'],healer:['Soaks und Fisch-Träger absichern.'],dps:['Fisch- und Kill-Reihenfolge strikt einhalten.']},difficulty:{heroic:'Aura of Unity erzwingt saubere Bosspositionen.',mythic:'Zusätzliche Rauminteraktionen bestrafen unkontrollierte Bewegung.'},sources:[['Wowhead',wowhead('lost-explorers')],['Warcraft Logs',warcraftLogs]]},
{id:'sszorak',order:5,name:'Sszorak',room:'Serpent Warren',type:'Knockbacks / Burstfenster',summary:'Bewegungsfight mit Push- und Knockback-Effekten. Dig In ist das wichtigste Schadensfenster; falsche Landepositionen sind der häufigste vermeidbare Fehler.',firstPull:['Vor jedem Knockback sichere Landefläche prüfen.','Viscous Cysts meiden.','Für Howling Maelstrom freie Gegenlaufwege halten.','CDs für Dig In vorbereiten.'],phases:[['Zyklus','Apex Predator → Venomous Surge → Knockbacks → Dig In.']],abilities:[['Venomous Surge','Erzeugt Globs und Viscous Cysts.'],['Viscous Cyst','Kontakt stößt Spieler weg.'],['Howling Maelstrom','Wind schiebt Spieler.'],['Dig In','Erhöhte Schadensaufnahme des Bosses.']],roles:{tank:['Boss mit Blick auf sichere Knockback-Zonen positionieren.'],healer:['Bewegungsphasen vorheilen.'],dps:['Offensive CDs für Dig In bündeln.']},difficulty:{heroic:'Mehr Raumgefahren machen falsche Landungen tödlicher.',mythic:'Persönliche Bewegungswege werden zu festen Assignments.'},sources:[['Wowhead',wowhead('sszorak')],['Warcraft Logs',warcraftLogs]]},
{id:'twin-fangs',order:6,name:'The Twin Fangs',room:'Pit of Fangs',type:'2 Ziele / Stack-Management',summary:'Vexhul und Ithraz bauen Eternal Venom auf Spielern auf. Bei 7 Anwendungen stirbt der Spieler; Ravenous Feast kann Stapel entfernen.',firstPull:['Eternal-Venom-Stapel beobachten.','Ravenous Feast gezielt zum Abbauen nutzen.','Caustic Deluge meiden.','Adds schnell kontrollieren.'],phases:[['Zyklus','Bossfähigkeiten bis 100 Energie.'],['100 Energie','Vile Flood und Sanguine Storm erhöhen Raum- und Raid-Druck.']],abilities:[['Eternal Venom','Persönlicher Stapel; 7 Anwendungen sind tödlich.'],['Ravenous Feast','Soak zum Abbauen von Stapeln.'],['Caustic Deluge','Globules erhöhen Eternal Venom.'],['Venomous Emergence','Beschwört Adds.']],roles:{tank:['Bosse kontrolliert stellen und Soak-Raum freihalten.'],healer:['Hohe Stack-Spieler beobachten.'],dps:['Stacks aktiv managen und Adds priorisieren.']},difficulty:{heroic:'Stack- und Raumfehler werden schwerer zu kompensieren.',mythic:'Feste Soakgruppen und ein klarer Stack-Plan sind Pflicht.'},sources:[['Wowhead',wowhead('twin-fangs')],['Warcraft Logs',warcraftLogs]]},
{id:'coiled-altar',order:7,name:'The Coiled Altar',room:'The Coiled Altar',type:'3 Phasen',summary:'Phase 1 gegen Zul’jan, Phase 2 gegen Hex Lord Malacrass; im Finale werden beide über ihre Seelenmechanik gemeinsam relevant.',firstPull:['Coalesced Venom kontrolliert beseitigen.','Tankhits gezielt für Raumobjekte nutzen.','Heil-CDs über drei Phasen verteilen.','Finalphase als Hauptcheck behandeln.'],phases:[['Phase 1','Zul’jan und Giftmechaniken.'],['Phase 2','Malacrass und Seelenmechaniken.'],['Finale','Beide Gegner werden gemeinsam relevant.']],abilities:[['Fangs of the Crucible','Hoher Raid-Schaden.'],['Coalesced Venom','Giftglobule mit Folgewirkung.'],['Venom Rupture','Raid-DoT nach Globule-Zerstörung.'],['Sever','Tankmechanik zum Bereinigen von Raumobjekten.'],['Soul Sever','Spätere Tank-/Seelenmechanik.']],roles:{tank:['Sever/Soul Sever bewusst einsetzen.'],healer:['Raid-Schadensfenster über Phasen verteilen.'],dps:['Globules nicht planlos zerstören.']},difficulty:{heroic:'Globule-Management wird strenger.',mythic:'Raumobjekte, Tankhits und finale Zielkontrolle müssen exakt zusammenspielen.'},sources:[['Wowhead',wowhead('coiled-altar')],['Warcraft Logs',warcraftLogs]]},
{id:'ulatek',order:8,name:"Ula'tek",room:"Ula'tek's Prison",type:'3 Phasen + Intermission',summary:'Endboss mit Area-Denial, Eiern/Adds und zunehmend zerstörter Arena. Venom-Kontakt kann Devourer’s Spawn ausbrüten und den Raid dauerhaft belasten.',firstPull:['Caustic Waves von Eiern fernhalten.','Adds nach Priorität töten.','Spectral Coils korrekt soaken.','Im Finale sicheren Raum gegen Demolish erhalten.'],phases:[['Phase 1','Caustic Waves, Eier und Spectral Coils.'],['Übergang','Rage of the Shackled und Venomous Heart.'],['Intermission','Adds und Eier kontrollieren.'],['Finale','Call of the Serpent + Demolish reduzieren sicheren Raum.']],abilities:[['Caustic Waves','Venomwellen verändern sichere Flächen.'],["Devourer's Spawn",'Eier, die gefährliche Adds hervorbringen.'],['Spectral Coils','Soak-Mechanik.'],['Rage of the Shackled','Großer Übergang.'],['Venomous Heart','Burstfenster.'],['Demolish','Zerstört sichere Arenabereiche.']],roles:{tank:['Boss/Adds mit Blick auf verbleibenden Raum führen.'],healer:['CDs für Übergänge und späte Raumknappheit staffeln.'],dps:['Adds/Eier nach Priorität spielen und Venomous Heart bursten.']},difficulty:{heroic:'Ungeplante Hatchings erhöhen den Heilbedarf dauerhaft.',mythic:'Eierbewegung und persönliche Abstände werden zu festen Assignments.'},sources:[['Blizzard',blizzard],['Wowhead',wowhead('ulatek')],['Warcraft Logs',warcraftLogs]]}
];
const roles={tank:['Tank',Shield],healer:['Heiler',HeartPulse],dps:['DPS',Sword]};
const safeArray=v=>Array.isArray(v)?v:[];
const currentSlug=()=>{const path=window.location.pathname.replace(/\/+$/,'');const relative=path.startsWith(BASE_PATH)?path.slice(BASE_PATH.length):path;return relative.replace(/^\/+|\/+$/g,'')||'nekzali'};
const bossHref=id=>`${BASE_PATH}/${id}`;
const criticalAbilities=new Set(['Soulcoil Well','Soulcoil Rite','Ritual of Awakening','Uncoiling',"Ula'tek's Dominance",'Contaminate','Vitriolic Stasis','Helical Toxins','Imbibe','Malignant Burst','Disgusting Fish','Mighty Thud','Aura of Unity','Howling Maelstrom','Eternal Venom','Ravenous Feast','Fangs of the Crucible','Sever','Soul Sever','Caustic Waves','Spectral Coils','Rage of the Shackled','Demolish']);
const routineAbilities=new Set(['Dig In','Venomous Heart','Blighted Blood','Infusion']);
const mechanicType=name=>{if(/soak|feast|coil|thud/i.test(name))return 'SOAK';if(/add|venom|spawn|amani|coagulation/i.test(name))return 'ADDS';if(/blood|contaminate|rite|uncoiling|rupture/i.test(name))return 'RAID DAMAGE';if(/sever|dominance/i.test(name))return 'TANK';if(/whisper|fish|stasis|awakening|imbibe/i.test(name))return 'MECHANIK';return 'AUSWEICHEN'};
function abilitySeverity(name){if(criticalAbilities.has(name))return{key:'critical',label:'KRITISCH',Icon:Skull};if(routineAbilities.has(name))return{key:'routine',label:'ROUTINE',Icon:CheckCircle2};return{key:'warning',label:'ACHTUNG',Icon:TriangleAlert}}
function Ability({item,difficulty}){const name=item?.[0]||'Unbekannte Fähigkeit';const note=item?.[1]||'';const severity=abilitySeverity(name);const Icon=severity.Icon;return <article className={`ability ability-${severity.key}`} title={`Deutsch: Live-Lokalisierung noch nicht final verifiziert\n${note}`}><div className="ability-icon"><Icon size={22}/></div><div className="ability-copy"><div className="ability-title"><strong>{name}</strong><div className="ability-badges"><span className="mechanic-badge">{mechanicType(name)}</span><span className="severity-badge">{severity.label}</span></div></div><p>{note}</p>{(difficulty==='mythic'||/Heroisch|Mythisch/i.test(note))&&<span className="difficulty-inline">{difficulty==='mythic'?'MYTHISCH':'HEROISCH'}</span>}</div></article>}
function QAStatus(){return <section className="qa-strip"><div><span className="online-dot"/><strong>Daten online</strong><small>Aktualisiert {updated}</small></div><div><CheckCircle2 size={16}/><strong>Blizzard / Wowhead</strong><small>Primärcheck aktiv</small></div><div><CheckCircle2 size={16}/><strong>Warcraft Logs</strong><small>Live-Pulls zur Plausibilisierung</small></div><div className="pending"><span className="online-dot"/><strong>Mythic Trap</strong><small>Venomous Abyss noch ausstehend</small></div></section>}
function App(){const[difficulty,setDifficulty]=useState('heroic');const[role,setRole]=useState('dps');const selected=currentSlug();const boss=bosses.find(b=>b.id===selected)||bosses[0];const[roleLabel,RoleIcon]=roles[role]||roles.dps;const roleItems=safeArray(boss.roles?.[role]||baseRoles[role]);return <div className="app"><header className="topbar"><div><span className="eyebrow">MIDNIGHT · PATCH 12.1</span><h1>The Venomous Abyss</h1><p>Raidguide für den ersten Pull. Ein schnelles und kurzes Nachschlagewerk für Raider.</p></div><div className="status"><span className="online-dot"/> Online · aktualisiert {updated}</div></header><QAStatus/><div className="layout"><aside className="sidebar"><div className="side-title">Bosse</div>{bosses.map(b=><a key={b.id} href={bossHref(b.id)} className={boss.id===b.id?'boss-btn active':'boss-btn'}><span>{b.order}</span><div><strong>{b.name}</strong><small>{b.type}</small></div></a>)}</aside><main className="content">
<section className="hero hero-upgraded"><div className="hero-copy"><div className="crumb">Boss {boss.order} / 8 · {boss.room}</div><h2>{boss.name}</h2><div className="encounter-tags"><span><Target size={13}/>{boss.type}</span><span><Users size={13}/>Raid Encounter</span></div><p className="boss-summary">{boss.summary}</p></div><div className="boss-portrait-placeholder"><div className="elite-ring"><Skull size={42}/></div><small>Bossbild folgt nach verifizierter Bildquelle</small></div><div className="controls"><div className="segmented"><button className={difficulty==='heroic'?'active':''} onClick={()=>setDifficulty('heroic')}>Heroisch</button><button className={difficulty==='mythic'?'active':''} onClick={()=>setDifficulty('mythic')}>Mythisch</button></div></div></section>
<section className="quick-card"><div className="quick-title"><Zap size={19}/><div><strong>Wenn du nur 30 Sekunden hast</strong><small>Das musst du vor dem Pull wissen</small></div></div><div className="quick-grid">{safeArray(boss.firstPull).slice(0,4).map((x,i)=><div key={i}><span>{i+1}</span><p>{x}</p></div>)}</div></section>
<div className="grid two boss-overview-grid"><section className="card pull-card"><h3><BookOpen/> Vor dem Pull wichtig:</h3><ol className="steps">{safeArray(boss.firstPull).map((x,i)=><li key={i}><span>{i+1}</span>{x}</li>)}</ol></section><section className="card flow-card"><h3><CircleDot/> Kampfablauf</h3><div className="phase-track">{safeArray(boss.phases).map((phase,i)=><React.Fragment key={i}><div className="phase-card"><span className="phase-index">{i+1}</span><strong>{phase?.[0]||`Phase ${i+1}`}</strong><p>{phase?.[1]||''}</p></div>{i<boss.phases.length-1&&<span className="phase-arrow">→</span>}</React.Fragment>)}</div></section></div>
<section className="card role-card role-focus"><div className="role-head"><div><span className="role-kicker">PERSÖNLICHER MINI-GUIDE</span><h3><RoleIcon/> Deine Aufgabe: {roleLabel}</h3></div><div className="role-tabs">{Object.entries(roles).map(([key,[label,Icon]])=><button key={key} className={role===key?'active':''} onClick={()=>setRole(key)}><Icon size={16}/>{label}</button>)}</div></div><div className="role-priority-grid">{roleItems.map((x,i)=><div className={`role-priority priority-${i}`} key={i}><span>{i===0?'PFLICHT':i===1?'PRIORITÄT':'OPTIMIERUNG'}</span><p>{x}</p></div>)}</div></section>
<section className="difficulty difficulty-upgraded"><span>{difficulty==='heroic'?'Heroisch':'Mythisch'}</span><p>{boss.difficulty?.[difficulty]||'Keine zusätzliche Änderung dokumentiert.'}</p></section>
<section className="card abilities-card"><div className="abilities-head"><div><span className="section-kicker">MECHANIKEN AUF EINEN BLICK</span><h3>Fähigkeiten</h3></div><div className="severity-legend"><span className="legend-critical">Kritisch</span><span className="legend-warning">Achtung</span><span className="legend-routine">Routine</span></div></div><div className="abilities">{safeArray(boss.abilities).map((x,i)=><Ability key={i} item={x} difficulty={difficulty}/>)}</div></section>
<details className="sources-collapsed"><summary><span><CheckCircle2 size={15}/> Daten geprüft · Aktualisiert {updated}</span><span>Quellen anzeigen <ChevronDown size={15}/></span></summary><div className="sources-body"><p>Blizzard/Wowhead plus Warcraft Logs werden gegengeprüft. Raum- und Positionsgrafiken bleiben ausgeblendet, bis belastbare Originalbilder verfügbar sind. Mythic Trap wird zweimal geprüft, sobald Venomous-Abyss-Guides öffentlich verfügbar sind.</p><div className="source-links">{safeArray(boss.sources).map((s,i)=><a href={s?.[1]||'#'} key={i} target="_blank" rel="noreferrer"><ExternalLink size={14}/>{s?.[0]||'Quelle'}</a>)}<a href={mythicTrap} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Mythic Trap · ausstehend</a></div></div></details>
</main></div></div>}
createRoot(document.getElementById('root')).render(<App/>);